Repository jrbourbeau/pyunfold, pull requests merged in 2018-05, with the labels that each got.

#27 Adds SplineRegularizer
  docs/api.rst
  docs/callbacks.rst
  docs/conf.py
  pyunfold/callbacks.py
  pyunfold/tests/test_callbacks.py
  pyunfold/unfold.py
Labels: enhancement

#52 Adding uniform prior, and correcting Jeffreys prior calculation
  docs/changelog.rst
  pyunfold/priors.py
  pyunfold/tests/test_priors.py
  pyunfold/tests/test_unfold.py
  pyunfold/unfold.py
Labels: enhancement, in progress

#47 Adds groups to SplineRegularizer
  docs/changelog.rst
  pyunfold/callbacks.py
  pyunfold/tests/test_callbacks.py
Labels: enhancement

#44 Adding paper files necessary for submission to JOSS
  docs/joss_paper/paper.bib
  docs/joss_paper/paper.md
Labels: documentation, in progress

#58 Adds advanced techniques section to documentation
  docs/source/advanced.rst
  docs/source/contributing.rst
  docs/source/index.rst
  docs/source/notebooks/multivariate.ipynb
  docs/source/notebooks/regularization.ipynb
  docs/source/notebooks/tutorial.ipynb
  docs/source/notebooks/user_prior.ipynb
Labels: documentation

#71 JOSS review-Add why pyunfold page
  docs/source/index.rst
  docs/source/overview.rst
  docs/source/why.rst
Labels: documentation, in progress

#73 Adding non-negative value check for input data objects
  docs/source/changelog.rst
  pyunfold/tests/test_unfold.py
  pyunfold/unfold.py
Labels: enhancement, in progress
